#[derive(Drop, Serde, Copy, PartialEq)]
enum Breakpoint {
    None,
    ReadCircuitParams,
    PrepRemGens,
    SqueezeChallengeScalars,
    PrepRemScalarPolys,
    PrepRemCommitments,
    PreMerkleInitialize,
    MerkleInitialize,
    AppendStatementCommitments,
    QueueVerification,
    StepVerification,
    SharesCommitment,
    MerkleInsert,
    HashStatement,
    CheckECDSA,
    PreInjectAndQueue,
    Party0ValidCommitments,
    Party0ValidReblind,
    Party1ValidCommitments,
    Party1ValidReblind,
    ValidMatchMpc,
    ValidSettle,
    CheckAndPoll,
}
