name: Install Cairo
description: Fetches Cairo1.0.0-alpha.6 and builds it. Assumes `cargo` has already been installed.
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: cache-cairo
      with:
        path: /cairo
        key: cairo
    - name: "[Cairo] Fetch source"
      if: steps.cache-cairo.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo mkdir -p /cairo &&
        sudo mkdir /cairo-tmp &&
        sudo git clone --branch v1.0.0-alpha.6 https://github.com/starkware-libs/cairo.git /cairo-tmp &&
        sudo cp -r /cairo-tmp/* /cairo
    - name: "[Cairo] Build source"
      if: steps.cache-cairo.outputs.cache-hit != 'true'
      shell: bash
      run: cd /cairo && sudo cargo build --release
    - name: "[Cairo] Make binaries available"
      shell: bash
      run: echo "/cairo/target/release" >> $GITHUB_PATH
